### ISSUE TITLE
Possible exception

### ISSUE THREAD

**Issue by Raffson** [abreens/sn#1]
https://github.com/abreens/sn/blob/dde191af9184a1b1dbb0fc8244083bc11773446a/les10/secretnumber2.py#L41

Om robuustheid te garanderen zou ik die de cast naar int op die lijn weglaten en een extra lijn toevoegen dat er als volgt uitziet:
`best_score = int(best_score) if best_score.isdigit() else None`
Zijnde een conditional statement dat best_score gelijk stelt aan None indien best_score niet uitsluitend bestaat uit cijfers.
https://github.com/abreens/sn/blob/dde191af9184a1b1dbb0fc8244083bc11773446a/les10/secretnumber2.py#L54
Als gevolg hiervan moet je op lijn 54 het if-statement ook aanpassen naar het volgende:
`if best_score is None or attempts < best_score`

**Comment by abreens** [comment]
Hi @Raffson,

Tx for the feedback.  Code blok werd als volgt aangepast:
```
best_score = score_file.read()
print("Huidige Top Score (attempts): " + best_score)
best_score = int(best_score) if best_score.isdigit() else None
```
