### ISSUE TITLE
Geography Quiz

### ISSUE THREAD

**Issue by Raffson** [abreens/sn#2]
https://github.com/abreens/sn/blob/16aae4c36b1f22e9e5cb8fd65ab6067f4ac127d7/les12/geographyquiz.py#L59
Om arbitraire fouten (bvb memory corruption) tegen te gaan is het beter om de conditie te definiëren als "aantal pogingen - i <= 0". Klein detail dat praktisch nooit zal voorkomen, maar het is altijd beter om met zulke zaken rekening te houden. 

https://github.com/abreens/sn/blob/16aae4c36b1f22e9e5cb8fd65ab6067f4ac127d7/les12/geographyquiz.py#L88
Desondanks het onmogelijk is dat de 'level' verschillend is van 'H', is het toch beter om
`elif level == 'H'` te gebruiken om de leesbaarheid/duidelijkheid te verbeteren. Uiteraard is dat een extra vergelijking die python zal moeten evalueren, maar in deze context zal de impact op de performantie praktisch geen verschil maken.

**Comment by abreens** [comment]
Aangepast in code!
