### ISSUE TITLE
Modular Secret

### ISSUE THREAD

**Issue by Raffson** [abreens/sn#3]
https://github.com/abreens/sn/blob/16aae4c36b1f22e9e5cb8fd65ab6067f4ac127d7/les12/modularsecret.py#L150
Hetzelfde verhaal als bij de Geography Quiz, hoewel dit op zich wel correct is. Hetzelfde geldt voor lijn 154.
https://github.com/abreens/sn/blob/16aae4c36b1f22e9e5cb8fd65ab6067f4ac127d7/les12/modularsecret.py#L154

**Comment by abreens** [comment]
Aangepast in code!
